### ISSUE TITLE
foundation site not building on Appveyor

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#637]
The foundation site doesn't seem to build on Appveyor anymore: 

https://ci.appveyor.com/project/mozillafoundation/network/history

It appears to be failing running `python -m pipenv run python network-api/manage.py collectstatic --no-input` - here's the stacktrace:
```
python -m pipenv run python network-api/manage.py collectstatic --no-input
C:\Users\appveyor\.virtualenvs\network-zohdQXq7\lib\site-packages\environ\environ.py:630: UserWarning: C:\projects\network\network-api\networkapi\.env doesn't exist - if you're not configuring your environment separately, create one.
  "environment separately, create one." % env_file)
Traceback (most recent call last):
  File "network-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\appveyor\.virtualenvs\network-zohdQXq7\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\appveyor\.virtualenvs\network-zohdQXq7\lib\site-packages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "C:\Users\appveyor\.virtualenvs\network-zohdQXq7\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\appveyor\.virtualenvs\network-zohdQXq7\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\appveyor\.virtualenvs\network-zohdQXq7\lib\site-packages\django\apps\config.py", line 120, in create
    mod = import_module(mod_path)
  File "C:\Users\appveyor\.virtualenvs\network-zohdQXq7\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wagtail.contrib'

```

@patjouk feel free to investigate this if you have the time, otherwise I'll pick it up in the morning.

**Comment by Pomax** [comment]
It also looks like we're using two different versions of python? That might be a problem...
```
Build started
ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
C:\Python36 3.6.x 32
[...snip...]
Requirement already satisfied: pip>=9.0.1 in c:\python27\lib\site-packages (from pipenv) (18.1)
Requirement already satisfied: virtualenv in c:\python27\lib\site-packages (from pipenv) (15.0.1)
```
So it looks like python 3.6 is available, but something's hooking into 2.7 instead.

**Comment by patjouk** [comment]
I'll look into it today.
The hash listed there are the hash for the pipefile.lock, not a comparison.

**Comment by patjouk** [comment]
Fixed 🎉
