### ISSUE TITLE
Fix coverage on python projects

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#724]
coverage is currently crashing for the foundation site and donate-wagtail:

```python
after_success
coveralls
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/coveralls", line 8, in <module>
    sys.exit(wear())
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coveralls/__init__.py", line 78, in wear
    from coveralls.control import coveralls
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coveralls/control.py", line 2, in <module>
    from coveralls.report import CoverallsReporter
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coveralls/report.py", line 6, in <module>
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter' from 'coverage.report' (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/report.py)
```

**Comment by patjouk** [comment]
python-coveralls doesn't seem to be maintained anymore and now breaks with the latest version of coverage. I'm replacing it with `coveralls-python` (https://github.com/coveralls-clients/coveralls-python).

To update:
- [ ] donate-wagtail
- [ ] foundation
~- pulse-api~ coveralls is not setup for pulse api
